CodeAcademy/Controllers/GroupController.cs
using CodeAcademy.DAL;
using CodeAcademy.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace CodeAcademy.Controllers
{
    public class GroupController : Controller
    {
        private readonly AppDbContext db;
        public GroupController(AppDbContext _db)
        {
            db = _db;
        }
        public async Task<IActionResult> Index()
        {

            GroupViewModel gvm = new GroupViewModel()
            {
                Groups = await db.Groups.Include(x => x.Category).Include(x => x.Teacher).ToListAsync(),
                Categories= await db.Categories.ToListAsync()
            };
            return View(gvm);
        }
        public async Task<IActionResult> GroupInfo()
        {

            GroupViewModel gvm = new GroupViewModel()
            {
                Groups = await db.Groups.Include(x => x.Students).Include(x => x.Teacher).ToListAsync(),
            };
            return View(gvm);
        }
    }
}

CodeAcademy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <title>Document</title>
</head>
<body>
    <nav id="navbar" class="navbar navbar-expand-lg navbar-light fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img id="white" src="~/assets/img/Logo.svg" style="height: 40px;">
                <img id="black" src="~/assets/img/Logo-black.svg" class="d-none" style="height: 40px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link fs-5" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item fs-5">
                        <a class="nav-link" href="#teachingAreas">Tədris sahaləri</a>
                    </li>
                    <li class="nav-item fs-5">
                        <a class="nav-link" href="#whyUs">Niyə biz</a>
                    </li>
                    <li class="nav-item fs-5">
                        <a class="nav-link" href="#contactUs">Əlaqə</a>
                    </li>
                    <li class="nav-item fs-5">
                        <a class="nav-link" asp-controller="Group" asp-action="Index">Qruplarımız</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="row p-3">
                <div class="col-md-6">
                    Site by &nbsp;<a class="text-decoration-none text-dark" href="github.com/thekarimovmurad"> Karimov Murad</a>
                </div>
                <div class="col-md-6">
                    Copyright © 2022. All rights reserved.
                </div>
            </div>
        </div>
    </footer><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js "
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin=" anonymous " referrerpolicy="no-referrer "></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js "
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p "
    crossorigin="anonymous "></script>

    <script src="~/assets/js/owl.carousel.min.js "></script>
    <script src="~/assets/js/main.js "></script>
</body>

</html>